schema_version: 1

context:
  name: azure-cosmos
  version: 4.6.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: daec6ac201c6473b092b62aee71e381beeb6c3a8dc361249832b7048c4f061e2

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools
    - requests >=2.10.0
    - six >=1.11.0
    - azure-core >=1.0.0,<2.0.0

tests:
  - python:
      imports:
        - azure.cosmos
      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE
  summary: Microsoft Azure Cosmos Python SDK
  description: Microsoft Azure Cosmos Python SDK
  homepage: https://github.com/Azure/azure-cosmos-python
  repository: https://github.com/Azure/azure-cosmos-python
  documentation: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-python

extra:
  recipe-maintainers:
    - yehoshuadimarsky
    - basnijholt
    - janjagusch
